apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80       # Port that the service will expose
      targetPort: 5000 # Port on the container
  type: LoadBalancer