apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  type: ClusterIP  # Ensure it's ClusterIP
  selector:
    app: mongodb   # Match the labels of the MongoDB pods
  ports:
    - protocol: TCP
      port: 27017  # Service port
      targetPort: 27017  # Port on the MongoDB pod