apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: alesb/tiny-web:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://mongodb-service:27017/mydatabase
        resources:
          limits:
            cpu: "500m"   # 100 milli CPUs
            memory: "128Mi" # 32 MiB of memory
          requests:
            cpu: "100m"    # 50 milli CPUs
            memory: "64Mi" # 16 MiB of memory
