version: '3.8'

services:
  mongodb:
    image: mongodb:v1.1
    volumes:
      - /vol:/data/db  # Mounts a volume for MongoDB data persistence
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "512M"

  web:
    image: tiny-web:v1.181
    ports:
      - "5000:5000"   # Exposing Flask app port to host
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "64M"

networks:
  my-network:
    driver: bridge
